WIP: commenting out function `distance` as a  stopgap to bypass python-fcl from not compiling ( again, 2.9 vs 3.1 probably to blaim )
there's a conversion issue at `fcl.pyx` at line 320, the function:

     def distance(self, *args):
        if len(args) == 2 and inspect.isfunction(args[1]):
            fn = DistanceFunction(args[1], args[0])
            self.thisptr.distance(<void*>fn, DistanceCallBack)
        elif len(args) == 3 and inspect.isfunction(args[2]):
            fn = DistanceFunction(args[2], args[1])
            self.thisptr.distance((<CollisionObject?>args[0]).thisptr, <void*>fn, DistanceCallBack)
        else:
            raise ValueError

won't compile because of some conversion issues:

fcl/fcl.cpp:8462:28: error: no matching member function for call to 'distance'
    __pyx_v_self->thisptr->distance(((void *)__pyx_v_fn), __pyx_f_3fcl_3fcl_DistanceCallBack);
    ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:129:8: note: candidate function
      not viable: no known conversion from 'bool (fcl::CollisionObject *, fcl::CollisionObject *, void *, double)' to
      'DistanceCallBack' (aka 'bool (*)(fcl::CollisionObject *, fcl::CollisionObject *, void *, FCL_REAL &)') for 2nd
      argument
  void distance(void* cdata, DistanceCallBack callback) const;
       ^
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:123:8: note: candidate function
      not viable: requires 3 arguments, but 2 were provided
  void distance(CollisionObject* obj, void* cdata, DistanceCallBack callback) const;
       ^
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:135:8: note: candidate function
      not viable: requires 3 arguments, but 2 were provided
  void distance(BroadPhaseCollisionManager* other_manager_, void* cdata, DistanceCallBack callback) const;
       ^
fcl/fcl.cpp:8556:28: error: no matching member function for call to 'distance'
    __pyx_v_self->thisptr->distance(((struct __pyx_obj_3fcl_3fcl_CollisionObject *)__pyx_t_4)->thisptr, ((voi...
    ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:123:8: note: candidate function
      not viable: no known conversion from 'bool (fcl::CollisionObject *, fcl::CollisionObject *, void *, double)' to
      'DistanceCallBack' (aka 'bool (*)(fcl::CollisionObject *, fcl::CollisionObject *, void *, FCL_REAL &)') for 3rd
      argument
  void distance(CollisionObject* obj, void* cdata, DistanceCallBack callback) const;
       ^
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:135:8: note: candidate function
      not viable: no known conversion from 'fcl::CollisionObject *' to 'fcl::BroadPhaseCollisionManager *' for 1st
      argument
  void distance(BroadPhaseCollisionManager* other_manager_, void* cdata, DistanceCallBack callback) const;
       ^
/Users/jelleferinga/miniconda/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h:129:8: note: candidate function
      not viable: requires 2 arguments, but 3 were provided
  void distance(void* cdata, DistanceCallBack callback) const;